# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'res/mods.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QThreadPool
from PyQt5.QtGui import QImage, QPixmap
from PyQt5.QtWidgets import QLabel


from tools.mods.modManager import listMod, toogleMod


class ModsManagerUI(object):
    profile = ''
    def setupUi(self, Form):
        Form.setObjectName("Mod installer")
        Form.resize(877, 731)
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(40, 260, 811, 441))
        self.listWidget.setObjectName("listWidget")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 20, 300, 441))
        self.label.setStyleSheet("QLabel{font-size: 18pt;}")
        self.label.setObjectName("label")


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def add_card(self, mod):
        itemN = QtWidgets.QListWidgetItem() 
        widget = QtWidgets.QWidget()

        widgetText =  QtWidgets.QLabel('aboba')
        widgetButton =  QtWidgets.QPushButton("Download")
        widgetLayout = QtWidgets.QHBoxLayout()
        widgetLayout.addWidget(widgetText)
        widgetLayout.addWidget(widgetButton)
        widgetLayout.addStretch()
        
        widgetLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        widget.setLayout(widgetLayout)  
        itemN.setSizeHint(widget.sizeHint())    
        
        self.listWidget.addItem(itemN)
        self.listWidget.setItemWidget(itemN, widget)
        
        #widgetButton.clicked.connect(lambda: self.on_click(modid))


    def retranslateUi(self, Form):
        Form.setWindowTitle(f'setup mod for {self.profile}')
        self.label.setText(f'setup mods for {self.profile}')
        for mod in listMod(self.profile):
            self.add_card(mod)
